WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 04:18:02] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 04:18:03] "[36mGET /static/plugins/fontawesome-free/css/all.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 04:18:03] "[36mGET /static/plugins/summernote/summernote-bs4.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 04:18:03] "[36mGET /static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 04:18:03] "[36mGET /static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 04:18:03] "[36mGET /static/dist/css/adminlte.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 04:18:03] "[36mGET /static/plugins/jqvmap/jqvmap.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 04:18:03] "[36mGET /static/plugins/icheck-bootstrap/icheck-bootstrap.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 04:18:03] "[36mGET /static/plugins/daterangepicker/daterangepicker.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 04:18:03] "[36mGET /static/plugins/summernote/summernote-bs4.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 04:18:04] "[36mGET /static/plugins/fontawesome-free/webfonts/fa-solid-900.woff2 HTTP/1.1[0m" 304 -
ERROR:main:Exception on /data [GET]
Traceback (most recent call last):
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Kuliah\intern2\main.py", line 11, in data
    data=list(dashboard().getDashboard.getResult())
AttributeError: 'function' object has no attribute 'getResult'
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 04:18:08] "[35m[1mGET /data HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
ERROR:main:Exception on /data [GET]
Traceback (most recent call last):
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Kuliah\intern2\main.py", line 11, in data
    data=list(dashboard().getDashboard().getResult())
TypeError: getDashboard() missing 1 required positional argument: 'data'
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 04:18:53] "[35m[1mGET /data HTTP/1.1[0m" 500 -
ERROR:main:Exception on /data [GET]
Traceback (most recent call last):
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Kuliah\intern2\main.py", line 11, in data
    data=list(dashboard().getDashboard().getResult())
TypeError: getDashboard() missing 1 required positional argument: 'data'
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 04:18:55] "[35m[1mGET /data HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 04:19:38] "GET /data HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 04:20:35] "GET /data HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 04:21:29] "GET /data HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
ERROR:main:Exception on /data [GET]
Traceback (most recent call last):
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Kuliah\intern2\main.py", line 16, in data
    data=list(data().getData().getResult())
UnboundLocalError: local variable 'data' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 04:35:47] "[35m[1mGET /data HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 04:37:27] "GET /data HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 04:38:46] "GET /data HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:18:23] "[33mGET /data HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:18:50] "[35m[1mGET /joiner HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:19:31] "[35m[1mGET /joiner HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:19:52] "[35m[1mGET /joiner HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
ERROR:main:Exception on /joiner [GET]
Traceback (most recent call last):
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Kuliah\intern2\main.py", line 27, in joiner
    templates_req = json.loads(templates['requirements'])
NameError: name 'json' is not defined
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:20:34] "[35m[1mGET /joiner HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
ERROR:main:Exception on /joiner [GET]
Traceback (most recent call last):
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Kuliah\intern2\main.py", line 28, in joiner
    templates_req = json.loads(templates['requirements'])
NameError: name 'templates' is not defined
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:20:52] "[35m[1mGET /joiner HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
ERROR:main:Exception on /joiner [GET]
Traceback (most recent call last):
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Kuliah\intern2\main.py", line 28, in joiner
    templates_req = json.loads(templates['requirements'])
  File "c:\users\lavy\appdata\local\programs\python\python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "c:\users\lavy\appdata\local\programs\python\python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\lavy\appdata\local\programs\python\python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:21:25] "[35m[1mGET /joiner HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
ERROR:main:Exception on /joiner [GET]
Traceback (most recent call last):
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Kuliah\intern2\main.py", line 28, in joiner
    templates_req = json.loads(templates['requirements'])
  File "c:\users\lavy\appdata\local\programs\python\python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "c:\users\lavy\appdata\local\programs\python\python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\lavy\appdata\local\programs\python\python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:22:26] "[35m[1mGET /joiner HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
ERROR:main:Exception on /joiner [GET]
Traceback (most recent call last):
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Kuliah\intern2\main.py", line 31, in joiner
    data_req = requests.get(data['url'])
NameError: name 'requests' is not defined
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:23:08] "[35m[1mGET /joiner HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:23:25] "GET /joiner HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:24:07] "GET /joiner HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
ERROR:main:Exception on /joiner [GET]
Traceback (most recent call last):
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Kuliah\intern2\main.py", line 37, in joiner
    keys = params_key.split('.')
AttributeError: 'dict' object has no attribute 'split'
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:24:59] "[35m[1mGET /joiner HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
ERROR:main:Exception on /joiner [GET]
Traceback (most recent call last):
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Kuliah\intern2\main.py", line 43, in joiner
    data_result = data_req_result[z]
KeyError: 'total_user'
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:25:29] "[35m[1mGET /joiner HTTP/1.1[0m" 500 -
ERROR:main:Exception on /joiner [GET]
Traceback (most recent call last):
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Kuliah\intern2\main.py", line 43, in joiner
    data_result = data_req_result[z]
KeyError: 'total_user'
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:26:19] "[35m[1mGET /joiner HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
ERROR:main:Exception on /joiner [GET]
Traceback (most recent call last):
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Kuliah\intern2\main.py", line 43, in joiner
    data_result = data_req_result[z]
KeyError: 'total_user'
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:26:27] "[35m[1mGET /joiner HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
ERROR:main:Exception on /joiner [GET]
Traceback (most recent call last):
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Kuliah\intern2\main.py", line 44, in joiner
    data_result = data_req_result[z]
KeyError: 'total_user'
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:27:07] "[35m[1mGET /joiner HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
ERROR:main:Exception on /joiner [GET]
Traceback (most recent call last):
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Kuliah\intern2\main.py", line 44, in joiner
    data_result = data_req_result[z]
KeyError: 'total_user'
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:27:57] "[35m[1mGET /joiner HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
ERROR:main:Exception on /joiner [GET]
Traceback (most recent call last):
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Kuliah\intern2\main.py", line 36, in joiner
    for y in params_key.keys():
RuntimeError: dictionary changed size during iteration
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:29:49] "[35m[1mGET /joiner HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:30:30] "GET /joiner HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:30:44] "GET /joiner HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
ERROR:main:Exception on /joiner [GET]
Traceback (most recent call last):
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Kuliah\intern2\main.py", line 47, in joiner
    dump[z] = params_key[z]
KeyError: 'total_user'
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:31:34] "[35m[1mGET /joiner HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:32:07] "GET /joiner HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:34:27] "GET /joiner HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:34:52] "GET /joiner HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:39:57] "GET /joiner HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:39:58] "[36mGET /static/plugins/fontawesome-free/css/all.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:39:58] "[36mGET /static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:39:58] "[36mGET /static/plugins/daterangepicker/daterangepicker.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:39:58] "[36mGET /static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:39:58] "[36mGET /static/plugins/icheck-bootstrap/icheck-bootstrap.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:39:58] "[36mGET /static/dist/css/adminlte.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:39:58] "[36mGET /static/plugins/jqvmap/jqvmap.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:39:59] "[36mGET /static/plugins/summernote/summernote-bs4.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:40:05] "[36mGET /static/plugins/fontawesome-free/css/all.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:40:05] "[36mGET /static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:40:05] "[36mGET /static/plugins/jqvmap/jqvmap.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:40:05] "[36mGET /static/plugins/icheck-bootstrap/icheck-bootstrap.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:40:05] "[36mGET /static/dist/css/adminlte.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:40:05] "[36mGET /static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:40:05] "[36mGET /static/plugins/daterangepicker/daterangepicker.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:40:05] "[36mGET /static/plugins/summernote/summernote-bs4.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:40:05] "GET /static/dist/css/adminlte.min.css.map HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
ERROR:main:Exception on /joiner [GET]
Traceback (most recent call last):
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Kuliah\intern2\main.py", line 50, in joiner
    return render_template('testing.html', data={"view":templates})
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "E:\Kuliah\intern2\venv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "E:\Kuliah\intern2\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\Kuliah\intern2\templates\testing.html", line 31, in top-level template code
    {{view.html}}
  File "E:\Kuliah\intern2\venv\lib\site-packages\jinja2\environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'view' is undefined
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:40:58] "[35m[1mGET /joiner HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:41:35] "GET /joiner HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:41:36] "[36mGET /static/plugins/fontawesome-free/css/all.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:41:37] "[36mGET /static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:41:37] "[36mGET /static/plugins/daterangepicker/daterangepicker.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:41:37] "[36mGET /static/plugins/jqvmap/jqvmap.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:41:37] "[36mGET /static/plugins/icheck-bootstrap/icheck-bootstrap.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:41:37] "[36mGET /static/dist/css/adminlte.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:41:37] "[36mGET /static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:41:37] "[36mGET /static/plugins/summernote/summernote-bs4.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:41:37] "GET /static/dist/css/adminlte.min.css.map HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.2.207:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:42:17] "GET /joiner HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:42:18] "[36mGET /static/plugins/fontawesome-free/css/all.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:42:19] "[36mGET /static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:42:19] "[36mGET /static/plugins/daterangepicker/daterangepicker.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:42:19] "[36mGET /static/plugins/icheck-bootstrap/icheck-bootstrap.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:42:19] "[36mGET /static/dist/css/adminlte.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:42:19] "[36mGET /static/plugins/jqvmap/jqvmap.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:42:19] "[36mGET /static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:42:19] "[36mGET /static/plugins/summernote/summernote-bs4.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:42:19] "GET /static/dist/css/adminlte.min.css.map HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:43:02] "GET /joiner HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:43:02] "[36mGET /static/plugins/fontawesome-free/css/all.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:43:02] "[36mGET /static/plugins/icheck-bootstrap/icheck-bootstrap.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:43:02] "[36mGET /static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:43:02] "[36mGET /static/plugins/jqvmap/jqvmap.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:43:02] "[36mGET /static/dist/css/adminlte.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:43:02] "[36mGET /static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:43:02] "[36mGET /static/plugins/daterangepicker/daterangepicker.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:43:02] "[36mGET /static/plugins/summernote/summernote-bs4.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2021 05:43:02] "GET /static/dist/css/adminlte.min.css.map HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.103:5000/ (Press CTRL+C to quit)
ERROR:main:Exception on / [GET]
Traceback (most recent call last):
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Kuliah\intern2\main.py", line 55, in read
    return render_template('testing.html')
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "E:\Kuliah\intern2\venv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "E:\Kuliah\intern2\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\Kuliah\intern2\templates\testing.html", line 31, in top-level template code
    {{data.view | safe}}
  File "E:\Kuliah\intern2\venv\lib\site-packages\jinja2\environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'data' is undefined
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 18:31:16] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 18:31:18] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.103:5000/ (Press CTRL+C to quit)
ERROR:main:Exception on / [GET]
Traceback (most recent call last):
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Kuliah\intern2\main.py", line 55, in read
    return render_template('testing.html')
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "E:\Kuliah\intern2\venv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "E:\Kuliah\intern2\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\Kuliah\intern2\templates\testing.html", line 31, in top-level template code
    {{data.view | safe}}
  File "E:\Kuliah\intern2\venv\lib\site-packages\jinja2\environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'data' is undefined
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 19:31:00] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 19:31:00] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
ERROR:main:Exception on / [GET]
Traceback (most recent call last):
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Kuliah\intern2\main.py", line 55, in read
    return render_template('testing.html')
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "E:\Kuliah\intern2\venv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "E:\Kuliah\intern2\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\Kuliah\intern2\templates\testing.html", line 31, in top-level template code
    {{data.view | safe}}
  File "E:\Kuliah\intern2\venv\lib\site-packages\jinja2\environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'data' is undefined
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 19:57:41] "[35m[1mGET / HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.103:5000/ (Press CTRL+C to quit)
ERROR:main:Exception on / [GET]
Traceback (most recent call last):
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Kuliah\intern2\main.py", line 55, in read
    return render_template('testing.html')
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "E:\Kuliah\intern2\venv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "E:\Kuliah\intern2\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\Kuliah\intern2\templates\testing.html", line 31, in top-level template code
    {{data.view | safe}}
  File "E:\Kuliah\intern2\venv\lib\site-packages\jinja2\environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'data' is undefined
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 19:59:00] "[35m[1mGET / HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.103:5000/ (Press CTRL+C to quit)
ERROR:main:Exception on / [GET]
Traceback (most recent call last):
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Kuliah\intern2\main.py", line 55, in read
    return render_template('testing.html')
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "E:\Kuliah\intern2\venv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "E:\Kuliah\intern2\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\Kuliah\intern2\templates\testing.html", line 31, in top-level template code
    {{data.view | safe}}
  File "E:\Kuliah\intern2\venv\lib\site-packages\jinja2\environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'data' is undefined
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 21:30:44] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 21:30:44] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 21:34:04] "GET /joiner HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 21:34:06] "[36mGET /static/plugins/icheck-bootstrap/icheck-bootstrap.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 21:34:06] "[36mGET /static/plugins/jqvmap/jqvmap.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 21:34:06] "[36mGET /static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 21:34:06] "[36mGET /static/plugins/fontawesome-free/css/all.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 21:34:06] "[36mGET /static/dist/css/adminlte.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 21:34:06] "[36mGET /static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 21:34:06] "[36mGET /static/plugins/daterangepicker/daterangepicker.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 21:34:06] "[36mGET /static/plugins/summernote/summernote-bs4.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 21:34:16] "[33mGET /data HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 21:34:21] "GET /joiner HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 21:34:21] "[36mGET /static/plugins/fontawesome-free/css/all.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 21:34:21] "[36mGET /static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 21:34:21] "[36mGET /static/plugins/icheck-bootstrap/icheck-bootstrap.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 21:34:21] "[36mGET /static/plugins/jqvmap/jqvmap.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 21:34:21] "[36mGET /static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 21:34:21] "[36mGET /static/dist/css/adminlte.min.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 21:34:21] "[36mGET /static/plugins/daterangepicker/daterangepicker.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 21:34:22] "[36mGET /static/plugins/summernote/summernote-bs4.min.css HTTP/1.1[0m" 304 -
ERROR:main:Exception on / [GET]
Traceback (most recent call last):
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Kuliah\intern2\main.py", line 55, in read
    return render_template('testing.html')
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "E:\Kuliah\intern2\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "E:\Kuliah\intern2\venv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "E:\Kuliah\intern2\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\Kuliah\intern2\templates\testing.html", line 31, in top-level template code
    {{data.view | safe}}
  File "E:\Kuliah\intern2\venv\lib\site-packages\jinja2\environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'data' is undefined
INFO:werkzeug:127.0.0.1 - - [04/Jun/2021 22:40:55] "[35m[1mGET / HTTP/1.1[0m" 500 -
